web_stuff/modern_web/web/router.ex
defmodule ModernWeb.Router do
  use ModernWeb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery

		plug SessionPlug
	  unless Mix.env != :prod, do: plug PlugStatsD
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ModernWeb do
    pipe_through :browser # Use the default browser stack

		resources "/roles", RoleController
		resources "/users", UserController

		get "/login", SessionController, :login
		post "/process_login", SessionController, :process_login
		delete "/logout", SessionController, :logout

    get "/", PageController, :index
		get "/new", PageController, :new
		post "/create", PageController, :create
		get "/show/:slug", PageController, :show
		get "/edit/:slug", PageController, :edit
		post "/update/:slug", PageController, :update
		delete "/delete/:slug", PageController, :delete
		#resources "/", PageController

    resources "/posts", PostController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ModernWeb do
  #   pipe_through :api
  # end
end

web_stuff/modern_web/web/views/layout_view.ex
defmodule ModernWeb.LayoutView do
  use ModernWeb.Web, :view

	# Import convenience functions from controllers
  import Phoenix.Controller, only: [get_flash: 2,
																		action_name: 1,
																		controller_module: 1] # Add these as imported

	def handler_info(conn) do
    "Request Handled By: #{controller_module conn}.#{action_name conn}"
  end
end

web_stuff/modern_web/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ModernWeb!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
	  <li><%= link "users", to: user_path(@conn, :index), class: "" %></li>
	  <li><%= link "blog", to: page_path(@conn, :index), class: "" %></li>
	  <li><%= link "posts", to: post_path(@conn, :index), class: "" %></li>
	  <%= if @username == "anonymous" do %>
	  <li>
	   <%= link "Login", to: session_path(@conn, :login), class: "" %> 
	  </li>
	  <% else %>
	  <li>
	    <i class="glyphicon glyphicon-user"></i>
	    <%= @username %>
	  </li>
	  <li>
	    <%= link "Logout", to: session_path(@conn, :logout), method: :delete, class: "btn btn-danger btn-xs" %>
	  </li>
	  <% end %>
        </ul>
        <span class="logo"></span>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <div class="jumbotron">

	<h2>The Modern Web!</h2>
	<p class="lead">Most frameworks make you choose between speed and a productive environment. <a href="http://phoenixframework.org">Phoenix</a> and <a href="http://elixir-lang.org">Elixir</a> give you both.</p>
	
	<p><%= handler_info @conn %></p>

      </div>
      
      <%= @inner %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app")</script>
  </body>
</html>

web_stuff/modern_web/web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ModernWeb!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
	  <li><%= link "users", to: user_path(@conn, :index), class: "" %></li>
	  <li><%= link "blog", to: page_path(@conn, :index), class: "" %></li>
	  <li><%= link "posts", to: post_path(@conn, :index), class: "" %></li>
	  <%= if @username == "anonymous" do %>
	  <li>
	   <%= link "Login", to: session_path(@conn, :login), class: "" %> 
	  </li>
	  <% else %>
	  <li>
	    <i class="glyphicon glyphicon-user"></i>
	    <%= @username %>
	  </li>
	  <li>
	    <%= link "Logout", to: session_path(@conn, :logout), method: :delete, class: "btn btn-danger btn-xs" %>
	  </li>
	  <% end %>
        </ul>
        <span class="logo"></span>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <div class="jumbotron">

	<h2>The Modern Web!</h2>
	<p class="lead">Most frameworks make you choose between speed and a productive environment. <a href="http://phoenixframework.org">Phoenix</a> and <a href="http://elixir-lang.org">Elixir</a> give you both.</p>
	
	<p><%= handler_info @conn %></p>

      </div>
      
      <%= @inner %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app")</script>
  </body>
</html>